# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSiteenable():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_generalenable(self):
    self.driver.get("http://prom-ecosystem-ruk-8340-dev.apps.ocpd.sib.evraz.com/general")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//td[contains(.,\'Распадская угольная компания\')]")))
    elements = self.driver.find_elements(By.XPATH, "//div[contains(text(), \'Распадская 7 пласт\')]")
    assert len(elements) > 0
  
  def test_generalwithoutwait(self):
    self.driver.get("http://prom-ecosystem-ruk-8340-dev.apps.ocpd.sib.evraz.com/general")
    elements = self.driver.find_elements(By.XPATH, "//div[contains(text(), \'Распадская 7 пласт\')]")
    assert len(elements) > 0
  
  def test_miningenable(self):
    self.driver.get("http://prom-ecosystem-ruk-8340-dev.apps.ocpd.sib.evraz.com/general")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//td[contains(.,\'Распадская угольная компания\')]")))
    elements = self.driver.find_elements(By.XPATH, "//div[contains(text(), \'Распадская 7 пласт\')]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".PageMines_tableRow__2LbSH:nth-child(2) > .PageMines_tableCell__1zmVY:nth-child(2)").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "section:nth-child(1) > .MiningTable_Body__yVFqt > .MiningTable_RowWrapper__2h2e_ > .MiningTable_RowWithDashlet__2Zq_s")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, "section:nth-child(1) > .MiningTable_Body__yVFqt > .MiningTable_RowWrapper__2h2e_ > .MiningTable_RowWithDashlet__2Zq_s")
    assert len(elements) > 0
  
